
query getArtists {

  artists {

    data {

      attributes {

        name
        surname
        role
        website
        description

        profilePic {
          data {
            attributes {
          		url
              ext
            }
          }
        }
        
        realisations {    
          data {
            attributes {
              url
              ext
            }
          }
        }

      }

    }

  }

}