query getHomeFolios {

  homefolios {
    
    data{
      
      attributes{
        
        title
        description
        visual{
          data{
            attributes{
              formats
              url
              ext
            }
          }
        }
        
      }
      
    }
    
  }

}